import random

def generate_plate():
    # KA-XX-YY-ZZZZ
    rto = random.randint(1, 70)
    rto_str = f"{rto:02d}"
    
    letters = "ABCDEFGHJKLMNPQRSTUVWXYZ"
    series = random.choice(letters) + random.choice(letters)
    
    number = random.randint(1, 9999)
    number_str = f"{number:04d}"
    
    return f"KA-{rto_str}-{series}-{number_str}"

owners = ["Ramesh", "Suresh", "Priya", "Rahul", "Aditi", "Kiran", "Vijay", "Lakshmi", "Anil", "Sunita", "Arun", "Deepa"]
statuses = ["Pending", "Pending", "Pending", "Completed"] # More pending than completed

sql_header = """
-- Create Table Logic (Safe to run if table doesn't exist)
CREATE TABLE IF NOT EXISTS challans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate TEXT NOT NULL,
    owner TEXT NOT NULL,
    amount BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO challans (plate, owner, amount, status) VALUES
"""
values = []

for _ in range(500):
    plate = generate_plate()
    owner = random.choice(owners)
    amount = random.choice([500, 1000, 2000, 100])
    status = random.choice(statuses)
    values.append(f"('{plate}', '{owner}', {amount}, '{status}')")

sql_content = sql_header + ",\n".join(values) + ";"

with open("seed_challans.sql", "w") as f:
    f.write(sql_content)

print("Generated seed_challans.sql with 500 records.")
